package com.surajshetty.atmos_flow.widget

// Generated by tool/widget_spec/emit_kotlin.py from the AtmosFlow Widgets
// design. Do not edit by hand — re-run the generator when the design moves.

object AmbientCatalog {
    /** The ambient sky for one condition under one of the five skies. */
    fun layers(condition: WidgetCondition, sky: WidgetSky): List<AmbientLayer> =
        when (condition to sky) {
            WidgetCondition.CLEAR to WidgetSky.DAWN -> listOf(
                AmbientLayer.DuskVeil(0.52f, 0x941A1424.toInt()),
                AmbientLayer.Radial(Box(left = Length.Pct(0.5f), bottom = Length.Frac(-0.225f), width = Length.Frac(0.45f), height = Length.Frac(0.45f), marginLeft = Length.Frac(-0.225f)), 0.5f, 0.5f, listOf(Stop(0xD9FFBE78.toInt()), Stop(0x33FFAA64.toInt(), 0.7f)), Anim("sunRise", 6f, 0f)),
                AmbientLayer.Fill(Box(top = Length.Frac(0.08f), left = Length.Pct(0.22f), width = Length.Dp(2f), height = Length.Dp(2f)), true, 0xFFFFFFFF.toInt(), null, Anim("twinkle", 3f, 0f)),
                AmbientLayer.Fill(Box(top = Length.Frac(0.16f), left = Length.Pct(0.68f), width = Length.Dp(2f), height = Length.Dp(2f)), true, 0xFFFFFFFF.toInt(), null, Anim("twinkle", 3.6f, 0.8f))
            )
            WidgetCondition.CLEAR to WidgetSky.MORNING -> listOf(
                AmbientLayer.Radial(Box(top = Length.Frac(-0.125f), right = Length.Frac(-0.125f), width = Length.Frac(0.54f), height = Length.Frac(0.54f)), 0.5f, 0.5f, listOf(Stop(0xBFFFD696.toInt()), Stop(0x00000000.toInt(), 0.7f)), Anim("sunPulse", 4f, 0f)),
                AmbientLayer.Ring(Box(top = Length.Frac(-0.2f), right = Length.Frac(-0.2f), width = Length.Frac(0.74f), height = Length.Frac(0.74f)), 2f, 0x33FFD696.toInt(), Anim("sunRaysRotate", 28f, 0f))
            )
            WidgetCondition.CLEAR to WidgetSky.AFTERNOON -> listOf(
                AmbientLayer.Radial(Box(top = Length.Pct(0.5f), left = Length.Pct(0.5f), width = Length.Frac(0.64f), height = Length.Frac(0.64f), marginTop = Length.Frac(-0.32f), marginLeft = Length.Frac(-0.32f)), 0.5f, 0.5f, listOf(Stop(0xE6FFEEBE.toInt()), Stop(0x00000000.toInt(), 0.68f)), Anim("sunPulse", 3f, 0f)),
                AmbientLayer.Ring(Box(top = Length.Pct(0.5f), left = Length.Pct(0.5f), width = Length.Frac(0.86f), height = Length.Frac(0.86f), marginTop = Length.Frac(-0.43f), marginLeft = Length.Frac(-0.43f)), 2f, 0x47FFEBB4.toInt(), Anim("sunRaysRotate", 22f, 0f))
            )
            WidgetCondition.CLEAR to WidgetSky.EVENING -> listOf(
                AmbientLayer.DuskVeil(0.52f, 0x941A1424.toInt()),
                AmbientLayer.Radial(Box(right = Length.Frac(0.11f), bottom = Length.Frac(-0.19f), width = Length.Frac(0.39f), height = Length.Frac(0.39f)), 0.5f, 0.5f, listOf(Stop(0xE6FFB46E.toInt()), Stop(0x40FF965A.toInt(), 0.7f)), Anim("moonGlow", 5f, 0f))
            )
            WidgetCondition.CLEAR to WidgetSky.NIGHT -> listOf(
                AmbientLayer.Radial(Box(top = Length.Frac(0.11f), right = Length.Frac(0.13f), width = Length.Frac(0.21f), height = Length.Frac(0.21f)), 0.38f, 0.34f, listOf(Stop(0xFFF4F0E2.toInt()), Stop(0xFFCFC9B4.toInt(), 0.72f)), Anim("moonGlow", 6f, 0f))
            )
            WidgetCondition.CLOUDY to WidgetSky.DAWN -> listOf(
                AmbientLayer.DuskVeil(0.52f, 0x941A1424.toInt()),
                AmbientLayer.Veil(0x709496A6.toInt(), null),
                AmbientLayer.Fill(Box(top = Length.Frac(0.09f), left = Length.Frac(-0.28f), width = Length.Frac(0.43f), height = Length.Frac(0.24f)), true, 0x5CFFFFFF.toInt(), null, Anim("cloudFloat", 6f, 0f)),
                AmbientLayer.Fill(Box(top = Length.Frac(0.48f), left = Length.Frac(-0.37f), width = Length.Frac(0.38f), height = Length.Frac(0.21f)), true, 0x42FFFFFF.toInt(), null, Anim("cloudFloat", 7f, 1.5f))
            )
            WidgetCondition.CLOUDY to WidgetSky.MORNING -> listOf(
                AmbientLayer.Veil(0x709496A6.toInt(), null),
                AmbientLayer.Fill(Box(top = Length.Frac(0.09f), left = Length.Frac(-0.28f), width = Length.Frac(0.43f), height = Length.Frac(0.24f)), true, 0x5CFFFFFF.toInt(), null, Anim("cloudFloat", 6f, 0f)),
                AmbientLayer.Fill(Box(top = Length.Frac(0.48f), left = Length.Frac(-0.37f), width = Length.Frac(0.38f), height = Length.Frac(0.21f)), true, 0x42FFFFFF.toInt(), null, Anim("cloudFloat", 7f, 1.5f))
            )
            WidgetCondition.CLOUDY to WidgetSky.AFTERNOON -> listOf(
                AmbientLayer.Veil(0x709496A6.toInt(), null),
                AmbientLayer.Fill(Box(top = Length.Frac(0.09f), left = Length.Frac(-0.28f), width = Length.Frac(0.43f), height = Length.Frac(0.24f)), true, 0x5CFFFFFF.toInt(), null, Anim("cloudFloat", 6f, 0f)),
                AmbientLayer.Fill(Box(top = Length.Frac(0.48f), left = Length.Frac(-0.37f), width = Length.Frac(0.38f), height = Length.Frac(0.21f)), true, 0x42FFFFFF.toInt(), null, Anim("cloudFloat", 7f, 1.5f))
            )
            WidgetCondition.CLOUDY to WidgetSky.EVENING -> listOf(
                AmbientLayer.DuskVeil(0.52f, 0x941A1424.toInt()),
                AmbientLayer.Veil(0x709496A6.toInt(), null),
                AmbientLayer.Fill(Box(top = Length.Frac(0.09f), left = Length.Frac(-0.28f), width = Length.Frac(0.43f), height = Length.Frac(0.24f)), true, 0x5CFFFFFF.toInt(), null, Anim("cloudFloat", 6f, 0f)),
                AmbientLayer.Fill(Box(top = Length.Frac(0.48f), left = Length.Frac(-0.37f), width = Length.Frac(0.38f), height = Length.Frac(0.21f)), true, 0x42FFFFFF.toInt(), null, Anim("cloudFloat", 7f, 1.5f))
            )
            WidgetCondition.CLOUDY to WidgetSky.NIGHT -> listOf(
                AmbientLayer.Veil(0x709496A6.toInt(), null),
                AmbientLayer.Fill(Box(top = Length.Frac(0.14f), left = Length.Pct(0.18f), width = Length.Dp(2f), height = Length.Dp(2f)), true, 0xFFFFFFFF.toInt(), null, Anim("twinkle", 2.8f, 0f)),
                AmbientLayer.Fill(Box(top = Length.Frac(0.27f), left = Length.Pct(0.36f), width = Length.Dp(2f), height = Length.Dp(2f)), true, 0xFFFFFFFF.toInt(), null, Anim("twinkle", 3.4f, 0.6f)),
                AmbientLayer.Fill(Box(top = Length.Frac(0.12f), left = Length.Pct(0.58f), width = Length.Dp(2f), height = Length.Dp(2f)), true, 0xFFFFFFFF.toInt(), null, Anim("twinkle", 3.1f, 1.2f)),
                AmbientLayer.Fill(Box(top = Length.Frac(0.09f), left = Length.Frac(-0.28f), width = Length.Frac(0.43f), height = Length.Frac(0.24f)), true, 0x5CFFFFFF.toInt(), null, Anim("cloudFloat", 6f, 0f)),
                AmbientLayer.Fill(Box(top = Length.Frac(0.48f), left = Length.Frac(-0.37f), width = Length.Frac(0.38f), height = Length.Frac(0.21f)), true, 0x42FFFFFF.toInt(), null, Anim("cloudFloat", 7f, 1.5f))
            )
            WidgetCondition.FOG to WidgetSky.DAWN -> listOf(
                AmbientLayer.DuskVeil(0.52f, 0x941A1424.toInt()),
                AmbientLayer.Veil(0x8FC4C6CE.toInt(), null),
                AmbientLayer.Mist(listOf(MistBlob(0.48f, 0.29f, 0.2f, 0.3f, 0x73E2E4EC.toInt()), MistBlob(0.57f, 0.33f, 0.75f, 0.7f, 0x59D6D8E2.toInt())), Anim("mistSwirl", 6f, 0f))
            )
            WidgetCondition.FOG to WidgetSky.MORNING -> listOf(
                AmbientLayer.Veil(0x8FC4C6CE.toInt(), null),
                AmbientLayer.Mist(listOf(MistBlob(0.48f, 0.29f, 0.2f, 0.3f, 0x73E2E4EC.toInt()), MistBlob(0.57f, 0.33f, 0.75f, 0.7f, 0x59D6D8E2.toInt())), Anim("mistSwirl", 6f, 0f))
            )
            WidgetCondition.FOG to WidgetSky.AFTERNOON -> listOf(
                AmbientLayer.Veil(0x8FC4C6CE.toInt(), null),
                AmbientLayer.Mist(listOf(MistBlob(0.48f, 0.29f, 0.2f, 0.3f, 0x73E2E4EC.toInt()), MistBlob(0.57f, 0.33f, 0.75f, 0.7f, 0x59D6D8E2.toInt())), Anim("mistSwirl", 6f, 0f))
            )
            WidgetCondition.FOG to WidgetSky.EVENING -> listOf(
                AmbientLayer.DuskVeil(0.52f, 0x941A1424.toInt()),
                AmbientLayer.Veil(0x8FC4C6CE.toInt(), null),
                AmbientLayer.Mist(listOf(MistBlob(0.48f, 0.29f, 0.2f, 0.3f, 0x73E2E4EC.toInt()), MistBlob(0.57f, 0.33f, 0.75f, 0.7f, 0x59D6D8E2.toInt())), Anim("mistSwirl", 6f, 0f))
            )
            WidgetCondition.FOG to WidgetSky.NIGHT -> listOf(
                AmbientLayer.Veil(0x8FC4C6CE.toInt(), null),
                AmbientLayer.Fill(Box(top = Length.Frac(0.14f), left = Length.Pct(0.18f), width = Length.Dp(2f), height = Length.Dp(2f)), true, 0xFFFFFFFF.toInt(), null, Anim("twinkle", 2.8f, 0f)),
                AmbientLayer.Fill(Box(top = Length.Frac(0.27f), left = Length.Pct(0.36f), width = Length.Dp(2f), height = Length.Dp(2f)), true, 0xFFFFFFFF.toInt(), null, Anim("twinkle", 3.4f, 0.6f)),
                AmbientLayer.Fill(Box(top = Length.Frac(0.12f), left = Length.Pct(0.58f), width = Length.Dp(2f), height = Length.Dp(2f)), true, 0xFFFFFFFF.toInt(), null, Anim("twinkle", 3.1f, 1.2f)),
                AmbientLayer.Mist(listOf(MistBlob(0.48f, 0.29f, 0.2f, 0.3f, 0x73E2E4EC.toInt()), MistBlob(0.57f, 0.33f, 0.75f, 0.7f, 0x59D6D8E2.toInt())), Anim("mistSwirl", 6f, 0f))
            )
            WidgetCondition.DRIZZLE to WidgetSky.DAWN -> listOf(
                AmbientLayer.DuskVeil(0.52f, 0x941A1424.toInt()),
                AmbientLayer.Veil(0x80545A70.toInt(), null),
                AmbientLayer.Fill(Box(top = Length.Frac(-0.1f), left = Length.Pct(0.1f), width = Length.Frac(0.009f), height = Length.Frac(0.1f)), false, 0x80D6E2F4.toInt(), null, Anim("rainFall", 1.6f, 0f)),
                AmbientLayer.Fill(Box(top = Length.Frac(-0.1f), left = Length.Pct(0.35f), width = Length.Frac(0.009f), height = Length.Frac(0.1f)), false, 0x80D6E2F4.toInt(), null, Anim("rainFall", 1.8f, 0.35f)),
                AmbientLayer.Fill(Box(top = Length.Frac(-0.1f), left = Length.Pct(0.6f), width = Length.Frac(0.009f), height = Length.Frac(0.1f)), false, 0x80D6E2F4.toInt(), null, Anim("rainFall", 1.7f, 0.2f)),
                AmbientLayer.Fill(Box(top = Length.Frac(-0.1f), left = Length.Pct(0.8f), width = Length.Frac(0.009f), height = Length.Frac(0.1f)), false, 0x80D6E2F4.toInt(), null, Anim("rainFall", 1.9f, 0.45f))
            )
            WidgetCondition.DRIZZLE to WidgetSky.MORNING -> listOf(
                AmbientLayer.Veil(0x80545A70.toInt(), null),
                AmbientLayer.Fill(Box(top = Length.Frac(-0.1f), left = Length.Pct(0.1f), width = Length.Frac(0.009f), height = Length.Frac(0.1f)), false, 0x80D6E2F4.toInt(), null, Anim("rainFall", 1.6f, 0f)),
                AmbientLayer.Fill(Box(top = Length.Frac(-0.1f), left = Length.Pct(0.35f), width = Length.Frac(0.009f), height = Length.Frac(0.1f)), false, 0x80D6E2F4.toInt(), null, Anim("rainFall", 1.8f, 0.35f)),
                AmbientLayer.Fill(Box(top = Length.Frac(-0.1f), left = Length.Pct(0.6f), width = Length.Frac(0.009f), height = Length.Frac(0.1f)), false, 0x80D6E2F4.toInt(), null, Anim("rainFall", 1.7f, 0.2f)),
                AmbientLayer.Fill(Box(top = Length.Frac(-0.1f), left = Length.Pct(0.8f), width = Length.Frac(0.009f), height = Length.Frac(0.1f)), false, 0x80D6E2F4.toInt(), null, Anim("rainFall", 1.9f, 0.45f))
            )
            WidgetCondition.DRIZZLE to WidgetSky.AFTERNOON -> listOf(
                AmbientLayer.Veil(0x80545A70.toInt(), null),
                AmbientLayer.Fill(Box(top = Length.Frac(-0.1f), left = Length.Pct(0.1f), width = Length.Frac(0.009f), height = Length.Frac(0.1f)), false, 0x80D6E2F4.toInt(), null, Anim("rainFall", 1.6f, 0f)),
                AmbientLayer.Fill(Box(top = Length.Frac(-0.1f), left = Length.Pct(0.35f), width = Length.Frac(0.009f), height = Length.Frac(0.1f)), false, 0x80D6E2F4.toInt(), null, Anim("rainFall", 1.8f, 0.35f)),
                AmbientLayer.Fill(Box(top = Length.Frac(-0.1f), left = Length.Pct(0.6f), width = Length.Frac(0.009f), height = Length.Frac(0.1f)), false, 0x80D6E2F4.toInt(), null, Anim("rainFall", 1.7f, 0.2f)),
                AmbientLayer.Fill(Box(top = Length.Frac(-0.1f), left = Length.Pct(0.8f), width = Length.Frac(0.009f), height = Length.Frac(0.1f)), false, 0x80D6E2F4.toInt(), null, Anim("rainFall", 1.9f, 0.45f))
            )
            WidgetCondition.DRIZZLE to WidgetSky.EVENING -> listOf(
                AmbientLayer.DuskVeil(0.52f, 0x941A1424.toInt()),
                AmbientLayer.Veil(0x80545A70.toInt(), null),
                AmbientLayer.Fill(Box(top = Length.Frac(-0.1f), left = Length.Pct(0.1f), width = Length.Frac(0.009f), height = Length.Frac(0.1f)), false, 0x80D6E2F4.toInt(), null, Anim("rainFall", 1.6f, 0f)),
                AmbientLayer.Fill(Box(top = Length.Frac(-0.1f), left = Length.Pct(0.35f), width = Length.Frac(0.009f), height = Length.Frac(0.1f)), false, 0x80D6E2F4.toInt(), null, Anim("rainFall", 1.8f, 0.35f)),
                AmbientLayer.Fill(Box(top = Length.Frac(-0.1f), left = Length.Pct(0.6f), width = Length.Frac(0.009f), height = Length.Frac(0.1f)), false, 0x80D6E2F4.toInt(), null, Anim("rainFall", 1.7f, 0.2f)),
                AmbientLayer.Fill(Box(top = Length.Frac(-0.1f), left = Length.Pct(0.8f), width = Length.Frac(0.009f), height = Length.Frac(0.1f)), false, 0x80D6E2F4.toInt(), null, Anim("rainFall", 1.9f, 0.45f))
            )
            WidgetCondition.DRIZZLE to WidgetSky.NIGHT -> listOf(
                AmbientLayer.Veil(0x80545A70.toInt(), null),
                AmbientLayer.Fill(Box(top = Length.Frac(0.14f), left = Length.Pct(0.18f), width = Length.Dp(2f), height = Length.Dp(2f)), true, 0xFFFFFFFF.toInt(), null, Anim("twinkle", 2.8f, 0f)),
                AmbientLayer.Fill(Box(top = Length.Frac(0.27f), left = Length.Pct(0.36f), width = Length.Dp(2f), height = Length.Dp(2f)), true, 0xFFFFFFFF.toInt(), null, Anim("twinkle", 3.4f, 0.6f)),
                AmbientLayer.Fill(Box(top = Length.Frac(0.12f), left = Length.Pct(0.58f), width = Length.Dp(2f), height = Length.Dp(2f)), true, 0xFFFFFFFF.toInt(), null, Anim("twinkle", 3.1f, 1.2f)),
                AmbientLayer.Fill(Box(top = Length.Frac(-0.1f), left = Length.Pct(0.1f), width = Length.Frac(0.009f), height = Length.Frac(0.1f)), false, 0x80D6E2F4.toInt(), null, Anim("rainFall", 1.6f, 0f)),
                AmbientLayer.Fill(Box(top = Length.Frac(-0.1f), left = Length.Pct(0.35f), width = Length.Frac(0.009f), height = Length.Frac(0.1f)), false, 0x80D6E2F4.toInt(), null, Anim("rainFall", 1.8f, 0.35f)),
                AmbientLayer.Fill(Box(top = Length.Frac(-0.1f), left = Length.Pct(0.6f), width = Length.Frac(0.009f), height = Length.Frac(0.1f)), false, 0x80D6E2F4.toInt(), null, Anim("rainFall", 1.7f, 0.2f)),
                AmbientLayer.Fill(Box(top = Length.Frac(-0.1f), left = Length.Pct(0.8f), width = Length.Frac(0.009f), height = Length.Frac(0.1f)), false, 0x80D6E2F4.toInt(), null, Anim("rainFall", 1.9f, 0.45f))
            )
            WidgetCondition.RAIN to WidgetSky.DAWN -> listOf(
                AmbientLayer.DuskVeil(0.52f, 0x941A1424.toInt()),
                AmbientLayer.Veil(0x94343A50.toInt(), null),
                AmbientLayer.Fill(Box(top = Length.Frac(-0.15f), left = Length.Pct(0.12f), width = Length.Dp(2f), height = Length.Frac(0.17f)), false, 0x99CEDEF2.toInt(), null, Anim("rainFall", 1.1f, 0f)),
                AmbientLayer.Fill(Box(top = Length.Frac(-0.15f), left = Length.Pct(0.32f), width = Length.Dp(2f), height = Length.Frac(0.17f)), false, 0x99CEDEF2.toInt(), null, Anim("rainFall", 1.3f, 0.15f)),
                AmbientLayer.Fill(Box(top = Length.Frac(-0.15f), left = Length.Pct(0.54f), width = Length.Dp(2f), height = Length.Frac(0.17f)), false, 0x99CEDEF2.toInt(), null, Anim("rainFall", 1.2f, 0.1f)),
                AmbientLayer.Fill(Box(top = Length.Frac(-0.15f), left = Length.Pct(0.74f), width = Length.Dp(2f), height = Length.Frac(0.17f)), false, 0x99CEDEF2.toInt(), null, Anim("rainFall", 1.4f, 0.25f)),
                AmbientLayer.Fill(Box(top = Length.Frac(-0.15f), left = Length.Pct(0.86f), width = Length.Dp(2f), height = Length.Frac(0.17f)), false, 0x99CEDEF2.toInt(), null, Anim("rainFall", 1.15f, 0.05f))
            )
            WidgetCondition.RAIN to WidgetSky.MORNING -> listOf(
                AmbientLayer.Veil(0x94343A50.toInt(), null),
                AmbientLayer.Fill(Box(top = Length.Frac(-0.15f), left = Length.Pct(0.12f), width = Length.Dp(2f), height = Length.Frac(0.17f)), false, 0x99CEDEF2.toInt(), null, Anim("rainFall", 1.1f, 0f)),
                AmbientLayer.Fill(Box(top = Length.Frac(-0.15f), left = Length.Pct(0.32f), width = Length.Dp(2f), height = Length.Frac(0.17f)), false, 0x99CEDEF2.toInt(), null, Anim("rainFall", 1.3f, 0.15f)),
                AmbientLayer.Fill(Box(top = Length.Frac(-0.15f), left = Length.Pct(0.54f), width = Length.Dp(2f), height = Length.Frac(0.17f)), false, 0x99CEDEF2.toInt(), null, Anim("rainFall", 1.2f, 0.1f)),
                AmbientLayer.Fill(Box(top = Length.Frac(-0.15f), left = Length.Pct(0.74f), width = Length.Dp(2f), height = Length.Frac(0.17f)), false, 0x99CEDEF2.toInt(), null, Anim("rainFall", 1.4f, 0.25f)),
                AmbientLayer.Fill(Box(top = Length.Frac(-0.15f), left = Length.Pct(0.86f), width = Length.Dp(2f), height = Length.Frac(0.17f)), false, 0x99CEDEF2.toInt(), null, Anim("rainFall", 1.15f, 0.05f))
            )
            WidgetCondition.RAIN to WidgetSky.AFTERNOON -> listOf(
                AmbientLayer.Veil(0x94343A50.toInt(), null),
                AmbientLayer.Fill(Box(top = Length.Frac(-0.15f), left = Length.Pct(0.12f), width = Length.Dp(2f), height = Length.Frac(0.17f)), false, 0x99CEDEF2.toInt(), null, Anim("rainFall", 1.1f, 0f)),
                AmbientLayer.Fill(Box(top = Length.Frac(-0.15f), left = Length.Pct(0.32f), width = Length.Dp(2f), height = Length.Frac(0.17f)), false, 0x99CEDEF2.toInt(), null, Anim("rainFall", 1.3f, 0.15f)),
                AmbientLayer.Fill(Box(top = Length.Frac(-0.15f), left = Length.Pct(0.54f), width = Length.Dp(2f), height = Length.Frac(0.17f)), false, 0x99CEDEF2.toInt(), null, Anim("rainFall", 1.2f, 0.1f)),
                AmbientLayer.Fill(Box(top = Length.Frac(-0.15f), left = Length.Pct(0.74f), width = Length.Dp(2f), height = Length.Frac(0.17f)), false, 0x99CEDEF2.toInt(), null, Anim("rainFall", 1.4f, 0.25f)),
                AmbientLayer.Fill(Box(top = Length.Frac(-0.15f), left = Length.Pct(0.86f), width = Length.Dp(2f), height = Length.Frac(0.17f)), false, 0x99CEDEF2.toInt(), null, Anim("rainFall", 1.15f, 0.05f))
            )
            WidgetCondition.RAIN to WidgetSky.EVENING -> listOf(
                AmbientLayer.DuskVeil(0.52f, 0x941A1424.toInt()),
                AmbientLayer.Veil(0x94343A50.toInt(), null),
                AmbientLayer.Fill(Box(top = Length.Frac(-0.15f), left = Length.Pct(0.12f), width = Length.Dp(2f), height = Length.Frac(0.17f)), false, 0x99CEDEF2.toInt(), null, Anim("rainFall", 1.1f, 0f)),
                AmbientLayer.Fill(Box(top = Length.Frac(-0.15f), left = Length.Pct(0.32f), width = Length.Dp(2f), height = Length.Frac(0.17f)), false, 0x99CEDEF2.toInt(), null, Anim("rainFall", 1.3f, 0.15f)),
                AmbientLayer.Fill(Box(top = Length.Frac(-0.15f), left = Length.Pct(0.54f), width = Length.Dp(2f), height = Length.Frac(0.17f)), false, 0x99CEDEF2.toInt(), null, Anim("rainFall", 1.2f, 0.1f)),
                AmbientLayer.Fill(Box(top = Length.Frac(-0.15f), left = Length.Pct(0.74f), width = Length.Dp(2f), height = Length.Frac(0.17f)), false, 0x99CEDEF2.toInt(), null, Anim("rainFall", 1.4f, 0.25f)),
                AmbientLayer.Fill(Box(top = Length.Frac(-0.15f), left = Length.Pct(0.86f), width = Length.Dp(2f), height = Length.Frac(0.17f)), false, 0x99CEDEF2.toInt(), null, Anim("rainFall", 1.15f, 0.05f))
            )
            WidgetCondition.RAIN to WidgetSky.NIGHT -> listOf(
                AmbientLayer.Veil(0x94343A50.toInt(), null),
                AmbientLayer.Fill(Box(top = Length.Frac(0.14f), left = Length.Pct(0.18f), width = Length.Dp(2f), height = Length.Dp(2f)), true, 0xFFFFFFFF.toInt(), null, Anim("twinkle", 2.8f, 0f)),
                AmbientLayer.Fill(Box(top = Length.Frac(0.27f), left = Length.Pct(0.36f), width = Length.Dp(2f), height = Length.Dp(2f)), true, 0xFFFFFFFF.toInt(), null, Anim("twinkle", 3.4f, 0.6f)),
                AmbientLayer.Fill(Box(top = Length.Frac(0.12f), left = Length.Pct(0.58f), width = Length.Dp(2f), height = Length.Dp(2f)), true, 0xFFFFFFFF.toInt(), null, Anim("twinkle", 3.1f, 1.2f)),
                AmbientLayer.Fill(Box(top = Length.Frac(-0.15f), left = Length.Pct(0.12f), width = Length.Dp(2f), height = Length.Frac(0.17f)), false, 0x99CEDEF2.toInt(), null, Anim("rainFall", 1.1f, 0f)),
                AmbientLayer.Fill(Box(top = Length.Frac(-0.15f), left = Length.Pct(0.32f), width = Length.Dp(2f), height = Length.Frac(0.17f)), false, 0x99CEDEF2.toInt(), null, Anim("rainFall", 1.3f, 0.15f)),
                AmbientLayer.Fill(Box(top = Length.Frac(-0.15f), left = Length.Pct(0.54f), width = Length.Dp(2f), height = Length.Frac(0.17f)), false, 0x99CEDEF2.toInt(), null, Anim("rainFall", 1.2f, 0.1f)),
                AmbientLayer.Fill(Box(top = Length.Frac(-0.15f), left = Length.Pct(0.74f), width = Length.Dp(2f), height = Length.Frac(0.17f)), false, 0x99CEDEF2.toInt(), null, Anim("rainFall", 1.4f, 0.25f)),
                AmbientLayer.Fill(Box(top = Length.Frac(-0.15f), left = Length.Pct(0.86f), width = Length.Dp(2f), height = Length.Frac(0.17f)), false, 0x99CEDEF2.toInt(), null, Anim("rainFall", 1.15f, 0.05f))
            )
            WidgetCondition.SNOW to WidgetSky.DAWN -> listOf(
                AmbientLayer.DuskVeil(0.52f, 0x941A1424.toInt()),
                AmbientLayer.Veil(0x80D6DEEE.toInt(), null),
                AmbientLayer.Fill(Box(top = Length.Frac(-0.07f), left = Length.Pct(0.1f), width = Length.Frac(0.02f), height = Length.Frac(0.02f)), true, 0xFFFFFFFF.toInt(), Glow(Length.Frac(0.015f), Length.Dp(0f), 0xCCFFFFFF.toInt()), Anim("rainFall", 2f, 0f)),
                AmbientLayer.Fill(Box(top = Length.Frac(-0.07f), left = Length.Pct(0.32f), width = Length.Frac(0.02f), height = Length.Frac(0.02f)), true, 0xFFFFFFFF.toInt(), Glow(Length.Frac(0.015f), Length.Dp(0f), 0xCCFFFFFF.toInt()), Anim("rainFall", 2.3f, 0.4f)),
                AmbientLayer.Fill(Box(top = Length.Frac(-0.07f), left = Length.Pct(0.54f), width = Length.Frac(0.02f), height = Length.Frac(0.02f)), true, 0xFFFFFFFF.toInt(), Glow(Length.Frac(0.015f), Length.Dp(0f), 0xCCFFFFFF.toInt()), Anim("rainFall", 2.1f, 0.2f)),
                AmbientLayer.Fill(Box(top = Length.Frac(-0.07f), left = Length.Pct(0.74f), width = Length.Frac(0.02f), height = Length.Frac(0.02f)), true, 0xFFFFFFFF.toInt(), Glow(Length.Frac(0.015f), Length.Dp(0f), 0xCCFFFFFF.toInt()), Anim("rainFall", 2.4f, 0.5f)),
                AmbientLayer.Fill(Box(top = Length.Frac(-0.07f), left = Length.Pct(0.86f), width = Length.Frac(0.02f), height = Length.Frac(0.02f)), true, 0xFFFFFFFF.toInt(), Glow(Length.Frac(0.015f), Length.Dp(0f), 0xCCFFFFFF.toInt()), Anim("rainFall", 2.2f, 0.3f))
            )
            WidgetCondition.SNOW to WidgetSky.MORNING -> listOf(
                AmbientLayer.Veil(0x80D6DEEE.toInt(), null),
                AmbientLayer.Fill(Box(top = Length.Frac(-0.07f), left = Length.Pct(0.1f), width = Length.Frac(0.02f), height = Length.Frac(0.02f)), true, 0xFFFFFFFF.toInt(), Glow(Length.Frac(0.015f), Length.Dp(0f), 0xCCFFFFFF.toInt()), Anim("rainFall", 2f, 0f)),
                AmbientLayer.Fill(Box(top = Length.Frac(-0.07f), left = Length.Pct(0.32f), width = Length.Frac(0.02f), height = Length.Frac(0.02f)), true, 0xFFFFFFFF.toInt(), Glow(Length.Frac(0.015f), Length.Dp(0f), 0xCCFFFFFF.toInt()), Anim("rainFall", 2.3f, 0.4f)),
                AmbientLayer.Fill(Box(top = Length.Frac(-0.07f), left = Length.Pct(0.54f), width = Length.Frac(0.02f), height = Length.Frac(0.02f)), true, 0xFFFFFFFF.toInt(), Glow(Length.Frac(0.015f), Length.Dp(0f), 0xCCFFFFFF.toInt()), Anim("rainFall", 2.1f, 0.2f)),
                AmbientLayer.Fill(Box(top = Length.Frac(-0.07f), left = Length.Pct(0.74f), width = Length.Frac(0.02f), height = Length.Frac(0.02f)), true, 0xFFFFFFFF.toInt(), Glow(Length.Frac(0.015f), Length.Dp(0f), 0xCCFFFFFF.toInt()), Anim("rainFall", 2.4f, 0.5f)),
                AmbientLayer.Fill(Box(top = Length.Frac(-0.07f), left = Length.Pct(0.86f), width = Length.Frac(0.02f), height = Length.Frac(0.02f)), true, 0xFFFFFFFF.toInt(), Glow(Length.Frac(0.015f), Length.Dp(0f), 0xCCFFFFFF.toInt()), Anim("rainFall", 2.2f, 0.3f))
            )
            WidgetCondition.SNOW to WidgetSky.AFTERNOON -> listOf(
                AmbientLayer.Veil(0x80D6DEEE.toInt(), null),
                AmbientLayer.Fill(Box(top = Length.Frac(-0.07f), left = Length.Pct(0.1f), width = Length.Frac(0.02f), height = Length.Frac(0.02f)), true, 0xFFFFFFFF.toInt(), Glow(Length.Frac(0.015f), Length.Dp(0f), 0xCCFFFFFF.toInt()), Anim("rainFall", 2f, 0f)),
                AmbientLayer.Fill(Box(top = Length.Frac(-0.07f), left = Length.Pct(0.32f), width = Length.Frac(0.02f), height = Length.Frac(0.02f)), true, 0xFFFFFFFF.toInt(), Glow(Length.Frac(0.015f), Length.Dp(0f), 0xCCFFFFFF.toInt()), Anim("rainFall", 2.3f, 0.4f)),
                AmbientLayer.Fill(Box(top = Length.Frac(-0.07f), left = Length.Pct(0.54f), width = Length.Frac(0.02f), height = Length.Frac(0.02f)), true, 0xFFFFFFFF.toInt(), Glow(Length.Frac(0.015f), Length.Dp(0f), 0xCCFFFFFF.toInt()), Anim("rainFall", 2.1f, 0.2f)),
                AmbientLayer.Fill(Box(top = Length.Frac(-0.07f), left = Length.Pct(0.74f), width = Length.Frac(0.02f), height = Length.Frac(0.02f)), true, 0xFFFFFFFF.toInt(), Glow(Length.Frac(0.015f), Length.Dp(0f), 0xCCFFFFFF.toInt()), Anim("rainFall", 2.4f, 0.5f)),
                AmbientLayer.Fill(Box(top = Length.Frac(-0.07f), left = Length.Pct(0.86f), width = Length.Frac(0.02f), height = Length.Frac(0.02f)), true, 0xFFFFFFFF.toInt(), Glow(Length.Frac(0.015f), Length.Dp(0f), 0xCCFFFFFF.toInt()), Anim("rainFall", 2.2f, 0.3f))
            )
            WidgetCondition.SNOW to WidgetSky.EVENING -> listOf(
                AmbientLayer.DuskVeil(0.52f, 0x941A1424.toInt()),
                AmbientLayer.Veil(0x80D6DEEE.toInt(), null),
                AmbientLayer.Fill(Box(top = Length.Frac(-0.07f), left = Length.Pct(0.1f), width = Length.Frac(0.02f), height = Length.Frac(0.02f)), true, 0xFFFFFFFF.toInt(), Glow(Length.Frac(0.015f), Length.Dp(0f), 0xCCFFFFFF.toInt()), Anim("rainFall", 2f, 0f)),
                AmbientLayer.Fill(Box(top = Length.Frac(-0.07f), left = Length.Pct(0.32f), width = Length.Frac(0.02f), height = Length.Frac(0.02f)), true, 0xFFFFFFFF.toInt(), Glow(Length.Frac(0.015f), Length.Dp(0f), 0xCCFFFFFF.toInt()), Anim("rainFall", 2.3f, 0.4f)),
                AmbientLayer.Fill(Box(top = Length.Frac(-0.07f), left = Length.Pct(0.54f), width = Length.Frac(0.02f), height = Length.Frac(0.02f)), true, 0xFFFFFFFF.toInt(), Glow(Length.Frac(0.015f), Length.Dp(0f), 0xCCFFFFFF.toInt()), Anim("rainFall", 2.1f, 0.2f)),
                AmbientLayer.Fill(Box(top = Length.Frac(-0.07f), left = Length.Pct(0.74f), width = Length.Frac(0.02f), height = Length.Frac(0.02f)), true, 0xFFFFFFFF.toInt(), Glow(Length.Frac(0.015f), Length.Dp(0f), 0xCCFFFFFF.toInt()), Anim("rainFall", 2.4f, 0.5f)),
                AmbientLayer.Fill(Box(top = Length.Frac(-0.07f), left = Length.Pct(0.86f), width = Length.Frac(0.02f), height = Length.Frac(0.02f)), true, 0xFFFFFFFF.toInt(), Glow(Length.Frac(0.015f), Length.Dp(0f), 0xCCFFFFFF.toInt()), Anim("rainFall", 2.2f, 0.3f))
            )
            WidgetCondition.SNOW to WidgetSky.NIGHT -> listOf(
                AmbientLayer.Veil(0x80D6DEEE.toInt(), null),
                AmbientLayer.Fill(Box(top = Length.Frac(0.14f), left = Length.Pct(0.18f), width = Length.Dp(2f), height = Length.Dp(2f)), true, 0xFFFFFFFF.toInt(), null, Anim("twinkle", 2.8f, 0f)),
                AmbientLayer.Fill(Box(top = Length.Frac(0.27f), left = Length.Pct(0.36f), width = Length.Dp(2f), height = Length.Dp(2f)), true, 0xFFFFFFFF.toInt(), null, Anim("twinkle", 3.4f, 0.6f)),
                AmbientLayer.Fill(Box(top = Length.Frac(0.12f), left = Length.Pct(0.58f), width = Length.Dp(2f), height = Length.Dp(2f)), true, 0xFFFFFFFF.toInt(), null, Anim("twinkle", 3.1f, 1.2f)),
                AmbientLayer.Fill(Box(top = Length.Frac(-0.07f), left = Length.Pct(0.1f), width = Length.Frac(0.02f), height = Length.Frac(0.02f)), true, 0xFFFFFFFF.toInt(), Glow(Length.Frac(0.015f), Length.Dp(0f), 0xCCFFFFFF.toInt()), Anim("rainFall", 2f, 0f)),
                AmbientLayer.Fill(Box(top = Length.Frac(-0.07f), left = Length.Pct(0.32f), width = Length.Frac(0.02f), height = Length.Frac(0.02f)), true, 0xFFFFFFFF.toInt(), Glow(Length.Frac(0.015f), Length.Dp(0f), 0xCCFFFFFF.toInt()), Anim("rainFall", 2.3f, 0.4f)),
                AmbientLayer.Fill(Box(top = Length.Frac(-0.07f), left = Length.Pct(0.54f), width = Length.Frac(0.02f), height = Length.Frac(0.02f)), true, 0xFFFFFFFF.toInt(), Glow(Length.Frac(0.015f), Length.Dp(0f), 0xCCFFFFFF.toInt()), Anim("rainFall", 2.1f, 0.2f)),
                AmbientLayer.Fill(Box(top = Length.Frac(-0.07f), left = Length.Pct(0.74f), width = Length.Frac(0.02f), height = Length.Frac(0.02f)), true, 0xFFFFFFFF.toInt(), Glow(Length.Frac(0.015f), Length.Dp(0f), 0xCCFFFFFF.toInt()), Anim("rainFall", 2.4f, 0.5f)),
                AmbientLayer.Fill(Box(top = Length.Frac(-0.07f), left = Length.Pct(0.86f), width = Length.Frac(0.02f), height = Length.Frac(0.02f)), true, 0xFFFFFFFF.toInt(), Glow(Length.Frac(0.015f), Length.Dp(0f), 0xCCFFFFFF.toInt()), Anim("rainFall", 2.2f, 0.3f))
            )
            WidgetCondition.STORM to WidgetSky.DAWN -> listOf(
                AmbientLayer.DuskVeil(0.52f, 0x941A1424.toInt()),
                AmbientLayer.Veil(0xA3181A2C.toInt(), null),
                AmbientLayer.Fill(Box(top = Length.Frac(-0.15f), left = Length.Pct(0.2f), width = Length.Frac(0.016f), height = Length.Frac(0.19f)), false, 0x8CE0E4F6.toInt(), null, Anim("rainFall", 1.2f, 0f)),
                AmbientLayer.Fill(Box(top = Length.Frac(-0.15f), left = Length.Pct(0.5f), width = Length.Frac(0.016f), height = Length.Frac(0.19f)), false, 0x8CE0E4F6.toInt(), null, Anim("rainFall", 1.4f, 0.2f)),
                AmbientLayer.Fill(Box(top = Length.Frac(-0.15f), left = Length.Pct(0.75f), width = Length.Frac(0.016f), height = Length.Frac(0.19f)), false, 0x8CE0E4F6.toInt(), null, Anim("rainFall", 1.3f, 0.1f)),
                AmbientLayer.Veil(0x38FFD078.toInt(), Anim("rainFallFlash", 3.2f, 0f))
            )
            WidgetCondition.STORM to WidgetSky.MORNING -> listOf(
                AmbientLayer.Veil(0xA3181A2C.toInt(), null),
                AmbientLayer.Fill(Box(top = Length.Frac(-0.15f), left = Length.Pct(0.2f), width = Length.Frac(0.016f), height = Length.Frac(0.19f)), false, 0x8CE0E4F6.toInt(), null, Anim("rainFall", 1.2f, 0f)),
                AmbientLayer.Fill(Box(top = Length.Frac(-0.15f), left = Length.Pct(0.5f), width = Length.Frac(0.016f), height = Length.Frac(0.19f)), false, 0x8CE0E4F6.toInt(), null, Anim("rainFall", 1.4f, 0.2f)),
                AmbientLayer.Fill(Box(top = Length.Frac(-0.15f), left = Length.Pct(0.75f), width = Length.Frac(0.016f), height = Length.Frac(0.19f)), false, 0x8CE0E4F6.toInt(), null, Anim("rainFall", 1.3f, 0.1f)),
                AmbientLayer.Veil(0x38FFD078.toInt(), Anim("rainFallFlash", 3.2f, 0f))
            )
            WidgetCondition.STORM to WidgetSky.AFTERNOON -> listOf(
                AmbientLayer.Veil(0xA3181A2C.toInt(), null),
                AmbientLayer.Fill(Box(top = Length.Frac(-0.15f), left = Length.Pct(0.2f), width = Length.Frac(0.016f), height = Length.Frac(0.19f)), false, 0x8CE0E4F6.toInt(), null, Anim("rainFall", 1.2f, 0f)),
                AmbientLayer.Fill(Box(top = Length.Frac(-0.15f), left = Length.Pct(0.5f), width = Length.Frac(0.016f), height = Length.Frac(0.19f)), false, 0x8CE0E4F6.toInt(), null, Anim("rainFall", 1.4f, 0.2f)),
                AmbientLayer.Fill(Box(top = Length.Frac(-0.15f), left = Length.Pct(0.75f), width = Length.Frac(0.016f), height = Length.Frac(0.19f)), false, 0x8CE0E4F6.toInt(), null, Anim("rainFall", 1.3f, 0.1f)),
                AmbientLayer.Veil(0x38FFD078.toInt(), Anim("rainFallFlash", 3.2f, 0f))
            )
            WidgetCondition.STORM to WidgetSky.EVENING -> listOf(
                AmbientLayer.DuskVeil(0.52f, 0x941A1424.toInt()),
                AmbientLayer.Veil(0xA3181A2C.toInt(), null),
                AmbientLayer.Fill(Box(top = Length.Frac(-0.15f), left = Length.Pct(0.2f), width = Length.Frac(0.016f), height = Length.Frac(0.19f)), false, 0x8CE0E4F6.toInt(), null, Anim("rainFall", 1.2f, 0f)),
                AmbientLayer.Fill(Box(top = Length.Frac(-0.15f), left = Length.Pct(0.5f), width = Length.Frac(0.016f), height = Length.Frac(0.19f)), false, 0x8CE0E4F6.toInt(), null, Anim("rainFall", 1.4f, 0.2f)),
                AmbientLayer.Fill(Box(top = Length.Frac(-0.15f), left = Length.Pct(0.75f), width = Length.Frac(0.016f), height = Length.Frac(0.19f)), false, 0x8CE0E4F6.toInt(), null, Anim("rainFall", 1.3f, 0.1f)),
                AmbientLayer.Veil(0x38FFD078.toInt(), Anim("rainFallFlash", 3.2f, 0f))
            )
            WidgetCondition.STORM to WidgetSky.NIGHT -> listOf(
                AmbientLayer.Veil(0xA3181A2C.toInt(), null),
                AmbientLayer.Fill(Box(top = Length.Frac(-0.15f), left = Length.Pct(0.2f), width = Length.Frac(0.016f), height = Length.Frac(0.19f)), false, 0x8CE0E4F6.toInt(), null, Anim("rainFall", 1.2f, 0f)),
                AmbientLayer.Fill(Box(top = Length.Frac(-0.15f), left = Length.Pct(0.5f), width = Length.Frac(0.016f), height = Length.Frac(0.19f)), false, 0x8CE0E4F6.toInt(), null, Anim("rainFall", 1.4f, 0.2f)),
                AmbientLayer.Fill(Box(top = Length.Frac(-0.15f), left = Length.Pct(0.75f), width = Length.Frac(0.016f), height = Length.Frac(0.19f)), false, 0x8CE0E4F6.toInt(), null, Anim("rainFall", 1.3f, 0.1f)),
                AmbientLayer.Veil(0x38FFD078.toInt(), Anim("rainFallFlash", 3.2f, 0f))
            )
            else -> emptyList()
        }
}
