name: atmos_flow
description: "AtmosFlow — a beautifully forecasted weather app."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  dio: ^5.11.0
  flutter:
    sdk: flutter
  flutter_riverpod: ^3.3.2
  freezed_annotation: ^3.1.0
  geocoding: ^5.0.0
  geolocator: ^14.0.2
  go_router: ^17.0.0
  intl: ^0.20.2
  json_annotation: ^4.9.0
  lucide_icons_flutter: ^3.1.15
  shared_preferences: ^2.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.7.1
  freezed: ^3.2.3
  json_serializable: ^6.11.2

flutter:
  uses-material-design: true

  fonts:
    - family: Caprasimo
      fonts:
        - asset: assets/fonts/Caprasimo-Regular.ttf
          weight: 400
    - family: Figtree
      fonts:
        - asset: assets/fonts/Figtree-Regular.ttf
          weight: 400
        - asset: assets/fonts/Figtree-SemiBold.ttf
          weight: 600
