"""The Kotlin half of the widget catalogue. See emit_swift.py."""
import json, os

HERE = os.path.dirname(os.path.abspath(__file__))
model = json.load(open(os.path.join(HERE, 'ambient_model.json')))

CONDITIONS = ['Clear', 'Cloudy', 'Fog', 'Drizzle', 'Rain', 'Snow', 'Storm']
SKIES = ['Dawn', 'Morning', 'Afternoon', 'Evening', 'Night']


def color(c):
    r, g, b, a = c
    return '0x%02X%02X%02X%02X.toInt()' % (round(a * 255), r, g, b)


def length(l):
    if l is None:
        return 'null'
    if 'frac' in l:
        return f'Length.Frac({l["frac"]:g}f)'
    if 'pct' in l:
        return f'Length.Pct({l["pct"]:g}f)'
    if 'px' in l:
        return f'Length.Dp({l["px"]:g}f)'
    raise ValueError(l)


def box(b):
    fields = [f'{k} = {length(b[k])}'
              for k in ('top', 'left', 'right', 'bottom', 'width', 'height',
                        'marginTop', 'marginLeft') if k in b]
    return 'Box(' + ', '.join(fields) + ')'


def anim(a):
    if not a:
        return 'null'
    return f'Anim("{a["name"]}", {a["duration"]:g}f, {a["delay"]:g}f)'


def stops(ss):
    return 'listOf(' + ', '.join(
        f'Stop({color(s["color"])}' + (f', {s["at"]:g}f' if s['at'] is not None else '') + ')'
        for s in ss) + ')'


def layer(l):
    kind = l['kind']
    if kind == 'veil':
        return f'AmbientLayer.Veil({color(l["color"])}, {anim(l["anim"])})'
    if kind == 'duskVeil':
        return f'AmbientLayer.DuskVeil({l["height"]:g}f, {color(l["color"])})'
    if kind == 'radial':
        cx, cy = l['center']
        return (f'AmbientLayer.Radial({box(l["box"])}, {cx:g}f, {cy:g}f, '
                f'{stops(l["stops"])}, {anim(l["anim"])})')
    if kind == 'ring':
        return (f'AmbientLayer.Ring({box(l["box"])}, {l["strokeWidth"]:g}f, '
                f'{color(l["color"])}, {anim(l["anim"])})')
    if kind == 'fill':
        glow = 'null'
        if 'glow' in l:
            g = l['glow']
            glow = f'Glow({length(g["blur"])}, {length(g["spread"])}, {color(g["color"])})'
        return (f'AmbientLayer.Fill({box(l["box"])}, {str(l["round"]).lower()}, '
                f'{color(l["color"])}, {glow}, {anim(l["anim"])})')
    if kind == 'mist':
        blobs = ', '.join(
            f'MistBlob({b["w"]:g}f, {b["h"]:g}f, {b["x"]:g}f, {b["y"]:g}f, {color(b["color"])})'
            for b in l['blobs'])
        return f'AmbientLayer.Mist(listOf({blobs}), {anim(l["anim"])})'
    raise ValueError(kind)


out = ['''package com.surajshetty.atmos_flow.widget

// Generated by tool/widget_spec/emit_kotlin.py from the AtmosFlow Widgets
// design. Do not edit by hand — re-run the generator when the design moves.

object AmbientCatalog {
    /** The ambient sky for one condition under one of the five skies. */
    fun layers(condition: WidgetCondition, sky: WidgetSky): List<AmbientLayer> =
        when (condition to sky) {''']

for c in CONDITIONS:
    for s in SKIES:
        body = ',\n                '.join(layer(l) for l in model[f'{c}|{s}'])
        out.append(f'            WidgetCondition.{c.upper()} to WidgetSky.{s.upper()} -> listOf(')
        out.append(f'                {body}\n            )')

out.append('''            else -> emptyList()
        }
}''')

path = os.path.join(HERE, '..', '..', 'android', 'app', 'src', 'main', 'kotlin',
                    'com', 'surajshetty', 'atmos_flow', 'widget', 'AmbientCatalog.kt')
open(path, 'w').write('\n'.join(out) + '\n')
print('wrote', os.path.normpath(path))
