"""Generate the widget ambient catalogue from the design's own CSS.

`ambient_model.json` is `parse_ambient.py`'s reading of every ambient layer in
the design project's `AtmosFlow Widgets.dc.html` — 7 conditions x 5 skies.
Hand-transcribing 35 layer sets would be 35 chances to mistype an alpha, so
the Swift and Kotlin catalogues are emitted from it instead.
"""
import json, sys, os

HERE = os.path.dirname(os.path.abspath(__file__))
model = json.load(open(os.path.join(HERE, 'ambient_model.json')))

CONDITIONS = ['Clear', 'Cloudy', 'Fog', 'Drizzle', 'Rain', 'Snow', 'Storm']
SKIES = ['Dawn', 'Morning', 'Afternoon', 'Evening', 'Night']


def color(c):
    r, g, b, a = c
    return f'.rgba({r}, {g}, {b}, {a:g})'


def length(l):
    if l is None:
        return 'nil'
    if 'frac' in l:
        return f'.frac({l["frac"]:g})'
    if 'pct' in l:
        return f'.pct({l["pct"]:g})'
    if 'px' in l:
        return f'.pt({l["px"]:g})'
    raise ValueError(l)


def box(b):
    fields = []
    for key in ('top', 'left', 'right', 'bottom', 'width', 'height',
                'marginTop', 'marginLeft'):
        if key in b:
            fields.append(f'{key}: {length(b[key])}')
    return 'Box(' + ', '.join(fields) + ')'


def anim(a):
    if not a:
        return 'nil'
    return f'Anim(name: "{a["name"]}", duration: {a["duration"]:g}, delay: {a["delay"]:g})'


def stops(ss):
    parts = []
    for s in ss:
        at = f', at: {s["at"]:g}' if s['at'] is not None else ''
        parts.append(f'Stop(color: {color(s["color"])}{at})')
    return '[' + ', '.join(parts) + ']'


def layer(l):
    kind = l['kind']
    if kind == 'veil':
        extra = '' if not l['anim'] else f', anim: {anim(l["anim"])}'
        return f'.veil({color(l["color"])}{extra})'
    if kind == 'duskVeil':
        return f'.duskVeil(height: {l["height"]:g}, color: {color(l["color"])})'
    if kind == 'radial':
        cx, cy = l['center']
        return (f'.radial({box(l["box"])}, '
                f'center: UnitPoint(x: {cx:g}, y: {cy:g}), '
                f'stops: {stops(l["stops"])}, anim: {anim(l["anim"])})')
    if kind == 'ring':
        return (f'.ring({box(l["box"])}, strokeWidth: {l["strokeWidth"]:g}, '
                f'color: {color(l["color"])}, anim: {anim(l["anim"])})')
    if kind == 'fill':
        glow = 'nil'
        if 'glow' in l:
            g = l['glow']
            glow = (f'Glow(blur: {length(g["blur"])}, '
                    f'spread: {length(g["spread"])}, color: {color(g["color"])})')
        return (f'.fill({box(l["box"])}, round: {str(l["round"]).lower()}, '
                f'color: {color(l["color"])}, glow: {glow}, anim: {anim(l["anim"])})')
    if kind == 'mist':
        blobs = ', '.join(
            f'MistBlob(width: {b["w"]:g}, height: {b["h"]:g}, '
            f'x: {b["x"]:g}, y: {b["y"]:g}, color: {color(b["color"])})'
            for b in l['blobs'])
        return f'.mist([{blobs}], anim: {anim(l["anim"])})'
    raise ValueError(kind)


out = ['''import SwiftUI

// Generated by tool/widget_spec/emit_swift.py from the AtmosFlow Widgets
// design. Do not edit by hand — re-run the generator when the design moves.

extension AmbientLayer {
    /// The ambient sky for one condition under one of the five skies.
    static func catalog(_ condition: WidgetCondition, _ sky: WidgetSky) -> [AmbientLayer] {
        switch (condition, sky) {''']

for c in CONDITIONS:
    for s in SKIES:
        layers = model[f'{c}|{s}']
        body = ',\n                '.join(layer(l) for l in layers)
        out.append(f'        case (.{c[0].lower() + c[1:]}, .{s[0].lower() + s[1:]}):')
        out.append(f'            return [\n                {body}\n            ]')

out.append('''        }
    }
}''')

path = os.path.join(HERE, '..', '..', 'ios', 'AtmosFlowWidget', 'AmbientCatalog.swift')
open(path, 'w').write('\n'.join(out) + '\n')
print('wrote', os.path.normpath(path), len(out), 'lines')
