import SwiftUI

// Generated by tool/widget_spec/emit_swift.py from the AtmosFlow Widgets
// design. Do not edit by hand — re-run the generator when the design moves.

extension AmbientLayer {
    /// The ambient sky for one condition under one of the five skies.
    static func catalog(_ condition: WidgetCondition, _ sky: WidgetSky) -> [AmbientLayer] {
        switch (condition, sky) {
        case (.clear, .dawn):
            return [
                .duskVeil(height: 0.52, color: .rgba(26, 20, 36, 0.58)),
                .radial(Box(left: .pct(0.5), bottom: .frac(-0.225), width: .frac(0.45), height: .frac(0.45), marginLeft: .frac(-0.225)), center: UnitPoint(x: 0.5, y: 0.5), stops: [Stop(color: .rgba(255, 190, 120, 0.85)), Stop(color: .rgba(255, 170, 100, 0.2), at: 0.7)], anim: Anim(name: "sunRise", duration: 6, delay: 0)),
                .fill(Box(top: .frac(0.08), left: .pct(0.22), width: .pt(2), height: .pt(2)), round: true, color: .rgba(255, 255, 255, 1), glow: nil, anim: Anim(name: "twinkle", duration: 3, delay: 0)),
                .fill(Box(top: .frac(0.16), left: .pct(0.68), width: .pt(2), height: .pt(2)), round: true, color: .rgba(255, 255, 255, 1), glow: nil, anim: Anim(name: "twinkle", duration: 3.6, delay: 0.8))
            ]
        case (.clear, .morning):
            return [
                .radial(Box(top: .frac(-0.125), right: .frac(-0.125), width: .frac(0.54), height: .frac(0.54)), center: UnitPoint(x: 0.5, y: 0.5), stops: [Stop(color: .rgba(255, 214, 150, 0.75)), Stop(color: .rgba(0, 0, 0, 0), at: 0.7)], anim: Anim(name: "sunPulse", duration: 4, delay: 0)),
                .ring(Box(top: .frac(-0.2), right: .frac(-0.2), width: .frac(0.74), height: .frac(0.74)), strokeWidth: 2, color: .rgba(255, 214, 150, 0.2), anim: Anim(name: "sunRaysRotate", duration: 28, delay: 0))
            ]
        case (.clear, .afternoon):
            return [
                .radial(Box(top: .pct(0.5), left: .pct(0.5), width: .frac(0.64), height: .frac(0.64), marginTop: .frac(-0.32), marginLeft: .frac(-0.32)), center: UnitPoint(x: 0.5, y: 0.5), stops: [Stop(color: .rgba(255, 238, 190, 0.9)), Stop(color: .rgba(0, 0, 0, 0), at: 0.68)], anim: Anim(name: "sunPulse", duration: 3, delay: 0)),
                .ring(Box(top: .pct(0.5), left: .pct(0.5), width: .frac(0.86), height: .frac(0.86), marginTop: .frac(-0.43), marginLeft: .frac(-0.43)), strokeWidth: 2, color: .rgba(255, 235, 180, 0.28), anim: Anim(name: "sunRaysRotate", duration: 22, delay: 0))
            ]
        case (.clear, .evening):
            return [
                .duskVeil(height: 0.52, color: .rgba(26, 20, 36, 0.58)),
                .radial(Box(right: .frac(0.11), bottom: .frac(-0.19), width: .frac(0.39), height: .frac(0.39)), center: UnitPoint(x: 0.5, y: 0.5), stops: [Stop(color: .rgba(255, 180, 110, 0.9)), Stop(color: .rgba(255, 150, 90, 0.25), at: 0.7)], anim: Anim(name: "moonGlow", duration: 5, delay: 0))
            ]
        case (.clear, .night):
            return [
                .radial(Box(top: .frac(0.11), right: .frac(0.13), width: .frac(0.21), height: .frac(0.21)), center: UnitPoint(x: 0.38, y: 0.34), stops: [Stop(color: .rgba(244, 240, 226, 1)), Stop(color: .rgba(207, 201, 180, 1), at: 0.72)], anim: Anim(name: "moonGlow", duration: 6, delay: 0))
            ]
        case (.cloudy, .dawn):
            return [
                .duskVeil(height: 0.52, color: .rgba(26, 20, 36, 0.58)),
                .veil(.rgba(148, 150, 166, 0.44)),
                .fill(Box(top: .frac(0.09), left: .frac(-0.28), width: .frac(0.43), height: .frac(0.24)), round: true, color: .rgba(255, 255, 255, 0.36), glow: nil, anim: Anim(name: "cloudFloat", duration: 6, delay: 0)),
                .fill(Box(top: .frac(0.48), left: .frac(-0.37), width: .frac(0.38), height: .frac(0.21)), round: true, color: .rgba(255, 255, 255, 0.26), glow: nil, anim: Anim(name: "cloudFloat", duration: 7, delay: 1.5))
            ]
        case (.cloudy, .morning):
            return [
                .veil(.rgba(148, 150, 166, 0.44)),
                .fill(Box(top: .frac(0.09), left: .frac(-0.28), width: .frac(0.43), height: .frac(0.24)), round: true, color: .rgba(255, 255, 255, 0.36), glow: nil, anim: Anim(name: "cloudFloat", duration: 6, delay: 0)),
                .fill(Box(top: .frac(0.48), left: .frac(-0.37), width: .frac(0.38), height: .frac(0.21)), round: true, color: .rgba(255, 255, 255, 0.26), glow: nil, anim: Anim(name: "cloudFloat", duration: 7, delay: 1.5))
            ]
        case (.cloudy, .afternoon):
            return [
                .veil(.rgba(148, 150, 166, 0.44)),
                .fill(Box(top: .frac(0.09), left: .frac(-0.28), width: .frac(0.43), height: .frac(0.24)), round: true, color: .rgba(255, 255, 255, 0.36), glow: nil, anim: Anim(name: "cloudFloat", duration: 6, delay: 0)),
                .fill(Box(top: .frac(0.48), left: .frac(-0.37), width: .frac(0.38), height: .frac(0.21)), round: true, color: .rgba(255, 255, 255, 0.26), glow: nil, anim: Anim(name: "cloudFloat", duration: 7, delay: 1.5))
            ]
        case (.cloudy, .evening):
            return [
                .duskVeil(height: 0.52, color: .rgba(26, 20, 36, 0.58)),
                .veil(.rgba(148, 150, 166, 0.44)),
                .fill(Box(top: .frac(0.09), left: .frac(-0.28), width: .frac(0.43), height: .frac(0.24)), round: true, color: .rgba(255, 255, 255, 0.36), glow: nil, anim: Anim(name: "cloudFloat", duration: 6, delay: 0)),
                .fill(Box(top: .frac(0.48), left: .frac(-0.37), width: .frac(0.38), height: .frac(0.21)), round: true, color: .rgba(255, 255, 255, 0.26), glow: nil, anim: Anim(name: "cloudFloat", duration: 7, delay: 1.5))
            ]
        case (.cloudy, .night):
            return [
                .veil(.rgba(148, 150, 166, 0.44)),
                .fill(Box(top: .frac(0.14), left: .pct(0.18), width: .pt(2), height: .pt(2)), round: true, color: .rgba(255, 255, 255, 1), glow: nil, anim: Anim(name: "twinkle", duration: 2.8, delay: 0)),
                .fill(Box(top: .frac(0.27), left: .pct(0.36), width: .pt(2), height: .pt(2)), round: true, color: .rgba(255, 255, 255, 1), glow: nil, anim: Anim(name: "twinkle", duration: 3.4, delay: 0.6)),
                .fill(Box(top: .frac(0.12), left: .pct(0.58), width: .pt(2), height: .pt(2)), round: true, color: .rgba(255, 255, 255, 1), glow: nil, anim: Anim(name: "twinkle", duration: 3.1, delay: 1.2)),
                .fill(Box(top: .frac(0.09), left: .frac(-0.28), width: .frac(0.43), height: .frac(0.24)), round: true, color: .rgba(255, 255, 255, 0.36), glow: nil, anim: Anim(name: "cloudFloat", duration: 6, delay: 0)),
                .fill(Box(top: .frac(0.48), left: .frac(-0.37), width: .frac(0.38), height: .frac(0.21)), round: true, color: .rgba(255, 255, 255, 0.26), glow: nil, anim: Anim(name: "cloudFloat", duration: 7, delay: 1.5))
            ]
        case (.fog, .dawn):
            return [
                .duskVeil(height: 0.52, color: .rgba(26, 20, 36, 0.58)),
                .veil(.rgba(196, 198, 206, 0.56)),
                .mist([MistBlob(width: 0.48, height: 0.29, x: 0.2, y: 0.3, color: .rgba(226, 228, 236, 0.45)), MistBlob(width: 0.57, height: 0.33, x: 0.75, y: 0.7, color: .rgba(214, 216, 226, 0.35))], anim: Anim(name: "mistSwirl", duration: 6, delay: 0))
            ]
        case (.fog, .morning):
            return [
                .veil(.rgba(196, 198, 206, 0.56)),
                .mist([MistBlob(width: 0.48, height: 0.29, x: 0.2, y: 0.3, color: .rgba(226, 228, 236, 0.45)), MistBlob(width: 0.57, height: 0.33, x: 0.75, y: 0.7, color: .rgba(214, 216, 226, 0.35))], anim: Anim(name: "mistSwirl", duration: 6, delay: 0))
            ]
        case (.fog, .afternoon):
            return [
                .veil(.rgba(196, 198, 206, 0.56)),
                .mist([MistBlob(width: 0.48, height: 0.29, x: 0.2, y: 0.3, color: .rgba(226, 228, 236, 0.45)), MistBlob(width: 0.57, height: 0.33, x: 0.75, y: 0.7, color: .rgba(214, 216, 226, 0.35))], anim: Anim(name: "mistSwirl", duration: 6, delay: 0))
            ]
        case (.fog, .evening):
            return [
                .duskVeil(height: 0.52, color: .rgba(26, 20, 36, 0.58)),
                .veil(.rgba(196, 198, 206, 0.56)),
                .mist([MistBlob(width: 0.48, height: 0.29, x: 0.2, y: 0.3, color: .rgba(226, 228, 236, 0.45)), MistBlob(width: 0.57, height: 0.33, x: 0.75, y: 0.7, color: .rgba(214, 216, 226, 0.35))], anim: Anim(name: "mistSwirl", duration: 6, delay: 0))
            ]
        case (.fog, .night):
            return [
                .veil(.rgba(196, 198, 206, 0.56)),
                .fill(Box(top: .frac(0.14), left: .pct(0.18), width: .pt(2), height: .pt(2)), round: true, color: .rgba(255, 255, 255, 1), glow: nil, anim: Anim(name: "twinkle", duration: 2.8, delay: 0)),
                .fill(Box(top: .frac(0.27), left: .pct(0.36), width: .pt(2), height: .pt(2)), round: true, color: .rgba(255, 255, 255, 1), glow: nil, anim: Anim(name: "twinkle", duration: 3.4, delay: 0.6)),
                .fill(Box(top: .frac(0.12), left: .pct(0.58), width: .pt(2), height: .pt(2)), round: true, color: .rgba(255, 255, 255, 1), glow: nil, anim: Anim(name: "twinkle", duration: 3.1, delay: 1.2)),
                .mist([MistBlob(width: 0.48, height: 0.29, x: 0.2, y: 0.3, color: .rgba(226, 228, 236, 0.45)), MistBlob(width: 0.57, height: 0.33, x: 0.75, y: 0.7, color: .rgba(214, 216, 226, 0.35))], anim: Anim(name: "mistSwirl", duration: 6, delay: 0))
            ]
        case (.drizzle, .dawn):
            return [
                .duskVeil(height: 0.52, color: .rgba(26, 20, 36, 0.58)),
                .veil(.rgba(84, 90, 112, 0.5)),
                .fill(Box(top: .frac(-0.1), left: .pct(0.1), width: .frac(0.009), height: .frac(0.1)), round: false, color: .rgba(214, 226, 244, 0.5), glow: nil, anim: Anim(name: "rainFall", duration: 1.6, delay: 0)),
                .fill(Box(top: .frac(-0.1), left: .pct(0.35), width: .frac(0.009), height: .frac(0.1)), round: false, color: .rgba(214, 226, 244, 0.5), glow: nil, anim: Anim(name: "rainFall", duration: 1.8, delay: 0.35)),
                .fill(Box(top: .frac(-0.1), left: .pct(0.6), width: .frac(0.009), height: .frac(0.1)), round: false, color: .rgba(214, 226, 244, 0.5), glow: nil, anim: Anim(name: "rainFall", duration: 1.7, delay: 0.2)),
                .fill(Box(top: .frac(-0.1), left: .pct(0.8), width: .frac(0.009), height: .frac(0.1)), round: false, color: .rgba(214, 226, 244, 0.5), glow: nil, anim: Anim(name: "rainFall", duration: 1.9, delay: 0.45))
            ]
        case (.drizzle, .morning):
            return [
                .veil(.rgba(84, 90, 112, 0.5)),
                .fill(Box(top: .frac(-0.1), left: .pct(0.1), width: .frac(0.009), height: .frac(0.1)), round: false, color: .rgba(214, 226, 244, 0.5), glow: nil, anim: Anim(name: "rainFall", duration: 1.6, delay: 0)),
                .fill(Box(top: .frac(-0.1), left: .pct(0.35), width: .frac(0.009), height: .frac(0.1)), round: false, color: .rgba(214, 226, 244, 0.5), glow: nil, anim: Anim(name: "rainFall", duration: 1.8, delay: 0.35)),
                .fill(Box(top: .frac(-0.1), left: .pct(0.6), width: .frac(0.009), height: .frac(0.1)), round: false, color: .rgba(214, 226, 244, 0.5), glow: nil, anim: Anim(name: "rainFall", duration: 1.7, delay: 0.2)),
                .fill(Box(top: .frac(-0.1), left: .pct(0.8), width: .frac(0.009), height: .frac(0.1)), round: false, color: .rgba(214, 226, 244, 0.5), glow: nil, anim: Anim(name: "rainFall", duration: 1.9, delay: 0.45))
            ]
        case (.drizzle, .afternoon):
            return [
                .veil(.rgba(84, 90, 112, 0.5)),
                .fill(Box(top: .frac(-0.1), left: .pct(0.1), width: .frac(0.009), height: .frac(0.1)), round: false, color: .rgba(214, 226, 244, 0.5), glow: nil, anim: Anim(name: "rainFall", duration: 1.6, delay: 0)),
                .fill(Box(top: .frac(-0.1), left: .pct(0.35), width: .frac(0.009), height: .frac(0.1)), round: false, color: .rgba(214, 226, 244, 0.5), glow: nil, anim: Anim(name: "rainFall", duration: 1.8, delay: 0.35)),
                .fill(Box(top: .frac(-0.1), left: .pct(0.6), width: .frac(0.009), height: .frac(0.1)), round: false, color: .rgba(214, 226, 244, 0.5), glow: nil, anim: Anim(name: "rainFall", duration: 1.7, delay: 0.2)),
                .fill(Box(top: .frac(-0.1), left: .pct(0.8), width: .frac(0.009), height: .frac(0.1)), round: false, color: .rgba(214, 226, 244, 0.5), glow: nil, anim: Anim(name: "rainFall", duration: 1.9, delay: 0.45))
            ]
        case (.drizzle, .evening):
            return [
                .duskVeil(height: 0.52, color: .rgba(26, 20, 36, 0.58)),
                .veil(.rgba(84, 90, 112, 0.5)),
                .fill(Box(top: .frac(-0.1), left: .pct(0.1), width: .frac(0.009), height: .frac(0.1)), round: false, color: .rgba(214, 226, 244, 0.5), glow: nil, anim: Anim(name: "rainFall", duration: 1.6, delay: 0)),
                .fill(Box(top: .frac(-0.1), left: .pct(0.35), width: .frac(0.009), height: .frac(0.1)), round: false, color: .rgba(214, 226, 244, 0.5), glow: nil, anim: Anim(name: "rainFall", duration: 1.8, delay: 0.35)),
                .fill(Box(top: .frac(-0.1), left: .pct(0.6), width: .frac(0.009), height: .frac(0.1)), round: false, color: .rgba(214, 226, 244, 0.5), glow: nil, anim: Anim(name: "rainFall", duration: 1.7, delay: 0.2)),
                .fill(Box(top: .frac(-0.1), left: .pct(0.8), width: .frac(0.009), height: .frac(0.1)), round: false, color: .rgba(214, 226, 244, 0.5), glow: nil, anim: Anim(name: "rainFall", duration: 1.9, delay: 0.45))
            ]
        case (.drizzle, .night):
            return [
                .veil(.rgba(84, 90, 112, 0.5)),
                .fill(Box(top: .frac(0.14), left: .pct(0.18), width: .pt(2), height: .pt(2)), round: true, color: .rgba(255, 255, 255, 1), glow: nil, anim: Anim(name: "twinkle", duration: 2.8, delay: 0)),
                .fill(Box(top: .frac(0.27), left: .pct(0.36), width: .pt(2), height: .pt(2)), round: true, color: .rgba(255, 255, 255, 1), glow: nil, anim: Anim(name: "twinkle", duration: 3.4, delay: 0.6)),
                .fill(Box(top: .frac(0.12), left: .pct(0.58), width: .pt(2), height: .pt(2)), round: true, color: .rgba(255, 255, 255, 1), glow: nil, anim: Anim(name: "twinkle", duration: 3.1, delay: 1.2)),
                .fill(Box(top: .frac(-0.1), left: .pct(0.1), width: .frac(0.009), height: .frac(0.1)), round: false, color: .rgba(214, 226, 244, 0.5), glow: nil, anim: Anim(name: "rainFall", duration: 1.6, delay: 0)),
                .fill(Box(top: .frac(-0.1), left: .pct(0.35), width: .frac(0.009), height: .frac(0.1)), round: false, color: .rgba(214, 226, 244, 0.5), glow: nil, anim: Anim(name: "rainFall", duration: 1.8, delay: 0.35)),
                .fill(Box(top: .frac(-0.1), left: .pct(0.6), width: .frac(0.009), height: .frac(0.1)), round: false, color: .rgba(214, 226, 244, 0.5), glow: nil, anim: Anim(name: "rainFall", duration: 1.7, delay: 0.2)),
                .fill(Box(top: .frac(-0.1), left: .pct(0.8), width: .frac(0.009), height: .frac(0.1)), round: false, color: .rgba(214, 226, 244, 0.5), glow: nil, anim: Anim(name: "rainFall", duration: 1.9, delay: 0.45))
            ]
        case (.rain, .dawn):
            return [
                .duskVeil(height: 0.52, color: .rgba(26, 20, 36, 0.58)),
                .veil(.rgba(52, 58, 80, 0.58)),
                .fill(Box(top: .frac(-0.15), left: .pct(0.12), width: .pt(2), height: .frac(0.17)), round: false, color: .rgba(206, 222, 242, 0.6), glow: nil, anim: Anim(name: "rainFall", duration: 1.1, delay: 0)),
                .fill(Box(top: .frac(-0.15), left: .pct(0.32), width: .pt(2), height: .frac(0.17)), round: false, color: .rgba(206, 222, 242, 0.6), glow: nil, anim: Anim(name: "rainFall", duration: 1.3, delay: 0.15)),
                .fill(Box(top: .frac(-0.15), left: .pct(0.54), width: .pt(2), height: .frac(0.17)), round: false, color: .rgba(206, 222, 242, 0.6), glow: nil, anim: Anim(name: "rainFall", duration: 1.2, delay: 0.1)),
                .fill(Box(top: .frac(-0.15), left: .pct(0.74), width: .pt(2), height: .frac(0.17)), round: false, color: .rgba(206, 222, 242, 0.6), glow: nil, anim: Anim(name: "rainFall", duration: 1.4, delay: 0.25)),
                .fill(Box(top: .frac(-0.15), left: .pct(0.86), width: .pt(2), height: .frac(0.17)), round: false, color: .rgba(206, 222, 242, 0.6), glow: nil, anim: Anim(name: "rainFall", duration: 1.15, delay: 0.05))
            ]
        case (.rain, .morning):
            return [
                .veil(.rgba(52, 58, 80, 0.58)),
                .fill(Box(top: .frac(-0.15), left: .pct(0.12), width: .pt(2), height: .frac(0.17)), round: false, color: .rgba(206, 222, 242, 0.6), glow: nil, anim: Anim(name: "rainFall", duration: 1.1, delay: 0)),
                .fill(Box(top: .frac(-0.15), left: .pct(0.32), width: .pt(2), height: .frac(0.17)), round: false, color: .rgba(206, 222, 242, 0.6), glow: nil, anim: Anim(name: "rainFall", duration: 1.3, delay: 0.15)),
                .fill(Box(top: .frac(-0.15), left: .pct(0.54), width: .pt(2), height: .frac(0.17)), round: false, color: .rgba(206, 222, 242, 0.6), glow: nil, anim: Anim(name: "rainFall", duration: 1.2, delay: 0.1)),
                .fill(Box(top: .frac(-0.15), left: .pct(0.74), width: .pt(2), height: .frac(0.17)), round: false, color: .rgba(206, 222, 242, 0.6), glow: nil, anim: Anim(name: "rainFall", duration: 1.4, delay: 0.25)),
                .fill(Box(top: .frac(-0.15), left: .pct(0.86), width: .pt(2), height: .frac(0.17)), round: false, color: .rgba(206, 222, 242, 0.6), glow: nil, anim: Anim(name: "rainFall", duration: 1.15, delay: 0.05))
            ]
        case (.rain, .afternoon):
            return [
                .veil(.rgba(52, 58, 80, 0.58)),
                .fill(Box(top: .frac(-0.15), left: .pct(0.12), width: .pt(2), height: .frac(0.17)), round: false, color: .rgba(206, 222, 242, 0.6), glow: nil, anim: Anim(name: "rainFall", duration: 1.1, delay: 0)),
                .fill(Box(top: .frac(-0.15), left: .pct(0.32), width: .pt(2), height: .frac(0.17)), round: false, color: .rgba(206, 222, 242, 0.6), glow: nil, anim: Anim(name: "rainFall", duration: 1.3, delay: 0.15)),
                .fill(Box(top: .frac(-0.15), left: .pct(0.54), width: .pt(2), height: .frac(0.17)), round: false, color: .rgba(206, 222, 242, 0.6), glow: nil, anim: Anim(name: "rainFall", duration: 1.2, delay: 0.1)),
                .fill(Box(top: .frac(-0.15), left: .pct(0.74), width: .pt(2), height: .frac(0.17)), round: false, color: .rgba(206, 222, 242, 0.6), glow: nil, anim: Anim(name: "rainFall", duration: 1.4, delay: 0.25)),
                .fill(Box(top: .frac(-0.15), left: .pct(0.86), width: .pt(2), height: .frac(0.17)), round: false, color: .rgba(206, 222, 242, 0.6), glow: nil, anim: Anim(name: "rainFall", duration: 1.15, delay: 0.05))
            ]
        case (.rain, .evening):
            return [
                .duskVeil(height: 0.52, color: .rgba(26, 20, 36, 0.58)),
                .veil(.rgba(52, 58, 80, 0.58)),
                .fill(Box(top: .frac(-0.15), left: .pct(0.12), width: .pt(2), height: .frac(0.17)), round: false, color: .rgba(206, 222, 242, 0.6), glow: nil, anim: Anim(name: "rainFall", duration: 1.1, delay: 0)),
                .fill(Box(top: .frac(-0.15), left: .pct(0.32), width: .pt(2), height: .frac(0.17)), round: false, color: .rgba(206, 222, 242, 0.6), glow: nil, anim: Anim(name: "rainFall", duration: 1.3, delay: 0.15)),
                .fill(Box(top: .frac(-0.15), left: .pct(0.54), width: .pt(2), height: .frac(0.17)), round: false, color: .rgba(206, 222, 242, 0.6), glow: nil, anim: Anim(name: "rainFall", duration: 1.2, delay: 0.1)),
                .fill(Box(top: .frac(-0.15), left: .pct(0.74), width: .pt(2), height: .frac(0.17)), round: false, color: .rgba(206, 222, 242, 0.6), glow: nil, anim: Anim(name: "rainFall", duration: 1.4, delay: 0.25)),
                .fill(Box(top: .frac(-0.15), left: .pct(0.86), width: .pt(2), height: .frac(0.17)), round: false, color: .rgba(206, 222, 242, 0.6), glow: nil, anim: Anim(name: "rainFall", duration: 1.15, delay: 0.05))
            ]
        case (.rain, .night):
            return [
                .veil(.rgba(52, 58, 80, 0.58)),
                .fill(Box(top: .frac(0.14), left: .pct(0.18), width: .pt(2), height: .pt(2)), round: true, color: .rgba(255, 255, 255, 1), glow: nil, anim: Anim(name: "twinkle", duration: 2.8, delay: 0)),
                .fill(Box(top: .frac(0.27), left: .pct(0.36), width: .pt(2), height: .pt(2)), round: true, color: .rgba(255, 255, 255, 1), glow: nil, anim: Anim(name: "twinkle", duration: 3.4, delay: 0.6)),
                .fill(Box(top: .frac(0.12), left: .pct(0.58), width: .pt(2), height: .pt(2)), round: true, color: .rgba(255, 255, 255, 1), glow: nil, anim: Anim(name: "twinkle", duration: 3.1, delay: 1.2)),
                .fill(Box(top: .frac(-0.15), left: .pct(0.12), width: .pt(2), height: .frac(0.17)), round: false, color: .rgba(206, 222, 242, 0.6), glow: nil, anim: Anim(name: "rainFall", duration: 1.1, delay: 0)),
                .fill(Box(top: .frac(-0.15), left: .pct(0.32), width: .pt(2), height: .frac(0.17)), round: false, color: .rgba(206, 222, 242, 0.6), glow: nil, anim: Anim(name: "rainFall", duration: 1.3, delay: 0.15)),
                .fill(Box(top: .frac(-0.15), left: .pct(0.54), width: .pt(2), height: .frac(0.17)), round: false, color: .rgba(206, 222, 242, 0.6), glow: nil, anim: Anim(name: "rainFall", duration: 1.2, delay: 0.1)),
                .fill(Box(top: .frac(-0.15), left: .pct(0.74), width: .pt(2), height: .frac(0.17)), round: false, color: .rgba(206, 222, 242, 0.6), glow: nil, anim: Anim(name: "rainFall", duration: 1.4, delay: 0.25)),
                .fill(Box(top: .frac(-0.15), left: .pct(0.86), width: .pt(2), height: .frac(0.17)), round: false, color: .rgba(206, 222, 242, 0.6), glow: nil, anim: Anim(name: "rainFall", duration: 1.15, delay: 0.05))
            ]
        case (.snow, .dawn):
            return [
                .duskVeil(height: 0.52, color: .rgba(26, 20, 36, 0.58)),
                .veil(.rgba(214, 222, 238, 0.5)),
                .fill(Box(top: .frac(-0.07), left: .pct(0.1), width: .frac(0.02), height: .frac(0.02)), round: true, color: .rgba(255, 255, 255, 1), glow: Glow(blur: .frac(0.015), spread: .pt(0), color: .rgba(255, 255, 255, 0.8)), anim: Anim(name: "rainFall", duration: 2, delay: 0)),
                .fill(Box(top: .frac(-0.07), left: .pct(0.32), width: .frac(0.02), height: .frac(0.02)), round: true, color: .rgba(255, 255, 255, 1), glow: Glow(blur: .frac(0.015), spread: .pt(0), color: .rgba(255, 255, 255, 0.8)), anim: Anim(name: "rainFall", duration: 2.3, delay: 0.4)),
                .fill(Box(top: .frac(-0.07), left: .pct(0.54), width: .frac(0.02), height: .frac(0.02)), round: true, color: .rgba(255, 255, 255, 1), glow: Glow(blur: .frac(0.015), spread: .pt(0), color: .rgba(255, 255, 255, 0.8)), anim: Anim(name: "rainFall", duration: 2.1, delay: 0.2)),
                .fill(Box(top: .frac(-0.07), left: .pct(0.74), width: .frac(0.02), height: .frac(0.02)), round: true, color: .rgba(255, 255, 255, 1), glow: Glow(blur: .frac(0.015), spread: .pt(0), color: .rgba(255, 255, 255, 0.8)), anim: Anim(name: "rainFall", duration: 2.4, delay: 0.5)),
                .fill(Box(top: .frac(-0.07), left: .pct(0.86), width: .frac(0.02), height: .frac(0.02)), round: true, color: .rgba(255, 255, 255, 1), glow: Glow(blur: .frac(0.015), spread: .pt(0), color: .rgba(255, 255, 255, 0.8)), anim: Anim(name: "rainFall", duration: 2.2, delay: 0.3))
            ]
        case (.snow, .morning):
            return [
                .veil(.rgba(214, 222, 238, 0.5)),
                .fill(Box(top: .frac(-0.07), left: .pct(0.1), width: .frac(0.02), height: .frac(0.02)), round: true, color: .rgba(255, 255, 255, 1), glow: Glow(blur: .frac(0.015), spread: .pt(0), color: .rgba(255, 255, 255, 0.8)), anim: Anim(name: "rainFall", duration: 2, delay: 0)),
                .fill(Box(top: .frac(-0.07), left: .pct(0.32), width: .frac(0.02), height: .frac(0.02)), round: true, color: .rgba(255, 255, 255, 1), glow: Glow(blur: .frac(0.015), spread: .pt(0), color: .rgba(255, 255, 255, 0.8)), anim: Anim(name: "rainFall", duration: 2.3, delay: 0.4)),
                .fill(Box(top: .frac(-0.07), left: .pct(0.54), width: .frac(0.02), height: .frac(0.02)), round: true, color: .rgba(255, 255, 255, 1), glow: Glow(blur: .frac(0.015), spread: .pt(0), color: .rgba(255, 255, 255, 0.8)), anim: Anim(name: "rainFall", duration: 2.1, delay: 0.2)),
                .fill(Box(top: .frac(-0.07), left: .pct(0.74), width: .frac(0.02), height: .frac(0.02)), round: true, color: .rgba(255, 255, 255, 1), glow: Glow(blur: .frac(0.015), spread: .pt(0), color: .rgba(255, 255, 255, 0.8)), anim: Anim(name: "rainFall", duration: 2.4, delay: 0.5)),
                .fill(Box(top: .frac(-0.07), left: .pct(0.86), width: .frac(0.02), height: .frac(0.02)), round: true, color: .rgba(255, 255, 255, 1), glow: Glow(blur: .frac(0.015), spread: .pt(0), color: .rgba(255, 255, 255, 0.8)), anim: Anim(name: "rainFall", duration: 2.2, delay: 0.3))
            ]
        case (.snow, .afternoon):
            return [
                .veil(.rgba(214, 222, 238, 0.5)),
                .fill(Box(top: .frac(-0.07), left: .pct(0.1), width: .frac(0.02), height: .frac(0.02)), round: true, color: .rgba(255, 255, 255, 1), glow: Glow(blur: .frac(0.015), spread: .pt(0), color: .rgba(255, 255, 255, 0.8)), anim: Anim(name: "rainFall", duration: 2, delay: 0)),
                .fill(Box(top: .frac(-0.07), left: .pct(0.32), width: .frac(0.02), height: .frac(0.02)), round: true, color: .rgba(255, 255, 255, 1), glow: Glow(blur: .frac(0.015), spread: .pt(0), color: .rgba(255, 255, 255, 0.8)), anim: Anim(name: "rainFall", duration: 2.3, delay: 0.4)),
                .fill(Box(top: .frac(-0.07), left: .pct(0.54), width: .frac(0.02), height: .frac(0.02)), round: true, color: .rgba(255, 255, 255, 1), glow: Glow(blur: .frac(0.015), spread: .pt(0), color: .rgba(255, 255, 255, 0.8)), anim: Anim(name: "rainFall", duration: 2.1, delay: 0.2)),
                .fill(Box(top: .frac(-0.07), left: .pct(0.74), width: .frac(0.02), height: .frac(0.02)), round: true, color: .rgba(255, 255, 255, 1), glow: Glow(blur: .frac(0.015), spread: .pt(0), color: .rgba(255, 255, 255, 0.8)), anim: Anim(name: "rainFall", duration: 2.4, delay: 0.5)),
                .fill(Box(top: .frac(-0.07), left: .pct(0.86), width: .frac(0.02), height: .frac(0.02)), round: true, color: .rgba(255, 255, 255, 1), glow: Glow(blur: .frac(0.015), spread: .pt(0), color: .rgba(255, 255, 255, 0.8)), anim: Anim(name: "rainFall", duration: 2.2, delay: 0.3))
            ]
        case (.snow, .evening):
            return [
                .duskVeil(height: 0.52, color: .rgba(26, 20, 36, 0.58)),
                .veil(.rgba(214, 222, 238, 0.5)),
                .fill(Box(top: .frac(-0.07), left: .pct(0.1), width: .frac(0.02), height: .frac(0.02)), round: true, color: .rgba(255, 255, 255, 1), glow: Glow(blur: .frac(0.015), spread: .pt(0), color: .rgba(255, 255, 255, 0.8)), anim: Anim(name: "rainFall", duration: 2, delay: 0)),
                .fill(Box(top: .frac(-0.07), left: .pct(0.32), width: .frac(0.02), height: .frac(0.02)), round: true, color: .rgba(255, 255, 255, 1), glow: Glow(blur: .frac(0.015), spread: .pt(0), color: .rgba(255, 255, 255, 0.8)), anim: Anim(name: "rainFall", duration: 2.3, delay: 0.4)),
                .fill(Box(top: .frac(-0.07), left: .pct(0.54), width: .frac(0.02), height: .frac(0.02)), round: true, color: .rgba(255, 255, 255, 1), glow: Glow(blur: .frac(0.015), spread: .pt(0), color: .rgba(255, 255, 255, 0.8)), anim: Anim(name: "rainFall", duration: 2.1, delay: 0.2)),
                .fill(Box(top: .frac(-0.07), left: .pct(0.74), width: .frac(0.02), height: .frac(0.02)), round: true, color: .rgba(255, 255, 255, 1), glow: Glow(blur: .frac(0.015), spread: .pt(0), color: .rgba(255, 255, 255, 0.8)), anim: Anim(name: "rainFall", duration: 2.4, delay: 0.5)),
                .fill(Box(top: .frac(-0.07), left: .pct(0.86), width: .frac(0.02), height: .frac(0.02)), round: true, color: .rgba(255, 255, 255, 1), glow: Glow(blur: .frac(0.015), spread: .pt(0), color: .rgba(255, 255, 255, 0.8)), anim: Anim(name: "rainFall", duration: 2.2, delay: 0.3))
            ]
        case (.snow, .night):
            return [
                .veil(.rgba(214, 222, 238, 0.5)),
                .fill(Box(top: .frac(0.14), left: .pct(0.18), width: .pt(2), height: .pt(2)), round: true, color: .rgba(255, 255, 255, 1), glow: nil, anim: Anim(name: "twinkle", duration: 2.8, delay: 0)),
                .fill(Box(top: .frac(0.27), left: .pct(0.36), width: .pt(2), height: .pt(2)), round: true, color: .rgba(255, 255, 255, 1), glow: nil, anim: Anim(name: "twinkle", duration: 3.4, delay: 0.6)),
                .fill(Box(top: .frac(0.12), left: .pct(0.58), width: .pt(2), height: .pt(2)), round: true, color: .rgba(255, 255, 255, 1), glow: nil, anim: Anim(name: "twinkle", duration: 3.1, delay: 1.2)),
                .fill(Box(top: .frac(-0.07), left: .pct(0.1), width: .frac(0.02), height: .frac(0.02)), round: true, color: .rgba(255, 255, 255, 1), glow: Glow(blur: .frac(0.015), spread: .pt(0), color: .rgba(255, 255, 255, 0.8)), anim: Anim(name: "rainFall", duration: 2, delay: 0)),
                .fill(Box(top: .frac(-0.07), left: .pct(0.32), width: .frac(0.02), height: .frac(0.02)), round: true, color: .rgba(255, 255, 255, 1), glow: Glow(blur: .frac(0.015), spread: .pt(0), color: .rgba(255, 255, 255, 0.8)), anim: Anim(name: "rainFall", duration: 2.3, delay: 0.4)),
                .fill(Box(top: .frac(-0.07), left: .pct(0.54), width: .frac(0.02), height: .frac(0.02)), round: true, color: .rgba(255, 255, 255, 1), glow: Glow(blur: .frac(0.015), spread: .pt(0), color: .rgba(255, 255, 255, 0.8)), anim: Anim(name: "rainFall", duration: 2.1, delay: 0.2)),
                .fill(Box(top: .frac(-0.07), left: .pct(0.74), width: .frac(0.02), height: .frac(0.02)), round: true, color: .rgba(255, 255, 255, 1), glow: Glow(blur: .frac(0.015), spread: .pt(0), color: .rgba(255, 255, 255, 0.8)), anim: Anim(name: "rainFall", duration: 2.4, delay: 0.5)),
                .fill(Box(top: .frac(-0.07), left: .pct(0.86), width: .frac(0.02), height: .frac(0.02)), round: true, color: .rgba(255, 255, 255, 1), glow: Glow(blur: .frac(0.015), spread: .pt(0), color: .rgba(255, 255, 255, 0.8)), anim: Anim(name: "rainFall", duration: 2.2, delay: 0.3))
            ]
        case (.storm, .dawn):
            return [
                .duskVeil(height: 0.52, color: .rgba(26, 20, 36, 0.58)),
                .veil(.rgba(24, 26, 44, 0.64)),
                .fill(Box(top: .frac(-0.15), left: .pct(0.2), width: .frac(0.016), height: .frac(0.19)), round: false, color: .rgba(224, 228, 246, 0.55), glow: nil, anim: Anim(name: "rainFall", duration: 1.2, delay: 0)),
                .fill(Box(top: .frac(-0.15), left: .pct(0.5), width: .frac(0.016), height: .frac(0.19)), round: false, color: .rgba(224, 228, 246, 0.55), glow: nil, anim: Anim(name: "rainFall", duration: 1.4, delay: 0.2)),
                .fill(Box(top: .frac(-0.15), left: .pct(0.75), width: .frac(0.016), height: .frac(0.19)), round: false, color: .rgba(224, 228, 246, 0.55), glow: nil, anim: Anim(name: "rainFall", duration: 1.3, delay: 0.1)),
                .veil(.rgba(255, 208, 120, 0.22), anim: Anim(name: "rainFallFlash", duration: 3.2, delay: 0))
            ]
        case (.storm, .morning):
            return [
                .veil(.rgba(24, 26, 44, 0.64)),
                .fill(Box(top: .frac(-0.15), left: .pct(0.2), width: .frac(0.016), height: .frac(0.19)), round: false, color: .rgba(224, 228, 246, 0.55), glow: nil, anim: Anim(name: "rainFall", duration: 1.2, delay: 0)),
                .fill(Box(top: .frac(-0.15), left: .pct(0.5), width: .frac(0.016), height: .frac(0.19)), round: false, color: .rgba(224, 228, 246, 0.55), glow: nil, anim: Anim(name: "rainFall", duration: 1.4, delay: 0.2)),
                .fill(Box(top: .frac(-0.15), left: .pct(0.75), width: .frac(0.016), height: .frac(0.19)), round: false, color: .rgba(224, 228, 246, 0.55), glow: nil, anim: Anim(name: "rainFall", duration: 1.3, delay: 0.1)),
                .veil(.rgba(255, 208, 120, 0.22), anim: Anim(name: "rainFallFlash", duration: 3.2, delay: 0))
            ]
        case (.storm, .afternoon):
            return [
                .veil(.rgba(24, 26, 44, 0.64)),
                .fill(Box(top: .frac(-0.15), left: .pct(0.2), width: .frac(0.016), height: .frac(0.19)), round: false, color: .rgba(224, 228, 246, 0.55), glow: nil, anim: Anim(name: "rainFall", duration: 1.2, delay: 0)),
                .fill(Box(top: .frac(-0.15), left: .pct(0.5), width: .frac(0.016), height: .frac(0.19)), round: false, color: .rgba(224, 228, 246, 0.55), glow: nil, anim: Anim(name: "rainFall", duration: 1.4, delay: 0.2)),
                .fill(Box(top: .frac(-0.15), left: .pct(0.75), width: .frac(0.016), height: .frac(0.19)), round: false, color: .rgba(224, 228, 246, 0.55), glow: nil, anim: Anim(name: "rainFall", duration: 1.3, delay: 0.1)),
                .veil(.rgba(255, 208, 120, 0.22), anim: Anim(name: "rainFallFlash", duration: 3.2, delay: 0))
            ]
        case (.storm, .evening):
            return [
                .duskVeil(height: 0.52, color: .rgba(26, 20, 36, 0.58)),
                .veil(.rgba(24, 26, 44, 0.64)),
                .fill(Box(top: .frac(-0.15), left: .pct(0.2), width: .frac(0.016), height: .frac(0.19)), round: false, color: .rgba(224, 228, 246, 0.55), glow: nil, anim: Anim(name: "rainFall", duration: 1.2, delay: 0)),
                .fill(Box(top: .frac(-0.15), left: .pct(0.5), width: .frac(0.016), height: .frac(0.19)), round: false, color: .rgba(224, 228, 246, 0.55), glow: nil, anim: Anim(name: "rainFall", duration: 1.4, delay: 0.2)),
                .fill(Box(top: .frac(-0.15), left: .pct(0.75), width: .frac(0.016), height: .frac(0.19)), round: false, color: .rgba(224, 228, 246, 0.55), glow: nil, anim: Anim(name: "rainFall", duration: 1.3, delay: 0.1)),
                .veil(.rgba(255, 208, 120, 0.22), anim: Anim(name: "rainFallFlash", duration: 3.2, delay: 0))
            ]
        case (.storm, .night):
            return [
                .veil(.rgba(24, 26, 44, 0.64)),
                .fill(Box(top: .frac(-0.15), left: .pct(0.2), width: .frac(0.016), height: .frac(0.19)), round: false, color: .rgba(224, 228, 246, 0.55), glow: nil, anim: Anim(name: "rainFall", duration: 1.2, delay: 0)),
                .fill(Box(top: .frac(-0.15), left: .pct(0.5), width: .frac(0.016), height: .frac(0.19)), round: false, color: .rgba(224, 228, 246, 0.55), glow: nil, anim: Anim(name: "rainFall", duration: 1.4, delay: 0.2)),
                .fill(Box(top: .frac(-0.15), left: .pct(0.75), width: .frac(0.016), height: .frac(0.19)), round: false, color: .rgba(224, 228, 246, 0.55), glow: nil, anim: Anim(name: "rainFall", duration: 1.3, delay: 0.1)),
                .veil(.rgba(255, 208, 120, 0.22), anim: Anim(name: "rainFallFlash", duration: 3.2, delay: 0))
            ]
        }
    }
}
